### ISSUE TITLE
Key Issue

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#143]
![image](https://user-images.githubusercontent.com/26223016/27938295-e69383ac-62b4-11e7-8fab-dd887f397057.png)

The key needs to be spread out a little, so it is more clear

**Comment by Samyoul** [comment]
### Additional Information:

Restructure the dashboard page so that the charts are shown in a 2x2 grid.

![dashboard](https://user-images.githubusercontent.com/5702426/31129859-b69ec24a-a84d-11e7-850e-1f93824510fe.png)

---

Orders by Status

PIE CHART

- Only show key elements if they are present
- If no statuses then show blank pie chart and only awaiting repair status

---

Summary data to be the same as the details for #146

**Comment by Samyoul** [comment]
Can we make sure that the summary box has an orange background and white font like the summary page.

**Comment by DalvinderSingh** [comment]
first one



-- 
Regards,

Dalvinder Singh Ghuman
Director
Diltek LTD
